### ISSUE TITLE
After Update cannot Install Search Plugins

### ISSUE THREAD

**Issue by Homesys-NJW** [qbittorrent/search-plugins#307]
After doing the latest update i cannot install the search plugins that i had in the previous version.
It gives the error - Cannot update "one377x" search plugin. Plugin not supported.

I have tried numerous plugins from my local plugin directory (note all worked on previous versions of gBittorrent) and also tried downloading the latest versions of the plugins from on-line.
![Plugin Error](https://github.com/user-attachments/assets/b81d1094-3bcc-4b2d-9e43-45214a5d0906)

I normally use the SAVE LINK AS function to a directory on my hard drive and it saves as a Python File Format OK (no change from previous usage)

Is the problem in the new version of qBittorrent or do I have to download ind reinstall Python.

Some help would be nice as I user the search feature fairly often.

Thanks for your time....

**Comment by denkiryu** [comment]
Same issue here, all my plugins were uninstalled after update, unable to reinstall.

**Comment by xavier2k6** [comment]
@sa3dany @Alyetama @BurningMop @scadams Update the `one337x.py` to be compatible with newer/latest version of python & review link for downloading plugin....most links are `raw` & not `gist`

**Comment by p060477** [comment]
> Found a fix, With qBit closed, went to "%localuserdata%\qBittorrent\nova3", renamed the "engines" folder to "engines1", reopened qBit and managed to drag-drop all the engines from the old folder straight to the "Install search plugins" window and they got installed.

do not fix at all my case... :(

**Comment by Astralyfuse** [comment]
> Found a fix, With qBit closed, went to "%localuserdata%\qBittorrent\nova3", renamed the "engines" folder to "engines1", reopened qBit and managed to drag-drop all the engines from the old folder straight to the "Install search plugins" window and they got installed.

This does work for me somehow, except not by drag and dropping, but just doing it like the usual with the "engines1" folder.
![image](https://github.com/user-attachments/assets/9db80ebb-25a9-4fb1-ac99-d38fd040b67c)

**Comment by p060477** [comment]
for me not fix at all...thxs anyway for yr kind effort

**Comment by fabio1999ita** [comment]
after complete delete from `%AppData%` and from `%AppData%/../Local` the qbittorrent folder and reinstalled it i get it works again

**Comment by p060477** [comment]
> after complete delete from `%AppData%` and from `%AppData%/../Local` the qbittorrent folder and reinstalled it i get it works again

unfurtunately not in my case...    i've the -portable- vers

**Comment by fabio1999ita** [comment]
> > after complete delete from `%AppData%` and from `%AppData%/../Local` the qbittorrent folder and reinstalled it i get it works again
> 
> unfurtunately not in my case... i've the -portable- vers

i have installed version 5.0.0 no qt6 one

**Comment by Homesys-NJW** [comment]
Hi all, Thanks for the help and all the great ideas.
I tried the repair of renaming the folder engine to engine1 then loading the files into qBittorrent again. I loaded some but not all the search engines I had.
I then deleted qBittorrent and all associated files and re-installed everything. tried a load of the search engine files i have on a local drive and they loaded as they should, but I lost all the special settings I had in qBittorrent

For myself I am considering this request closed but the original problem of the search engine not loading or carrying over on the upgrade still exists.
Hope all others find a workaround to the problem they have that is similar.

**Comment by Pogman** [comment]
My FIX:

Stop QBT and open Win Settings -> Apps
Search for and uninstall any old Python versions
Get the latest Python from here:
https://www.python.org/downloads/windows/
Install - Run QBT and whatever plugins you had previously should now work and you can install new ones too.

**Comment by p060477** [comment]
> My FIX:
> 
> Stop QBT and open Win Settings -> Apps Search for and uninstall any old Python versions Get the latest Python from here: https://www.python.org/downloads/windows/ Install - Run QBT and whatever plugins you had previously should now work and you can install new ones too.

thxs so muc...but...i've done this everytime a new vers come...for me..i repeat -for me- did not fix at all

**Comment by mirco982** [comment]
What about macOS users?? Any advice?

**Comment by p060477** [comment]
> @mirco982
> 
> There seem to be multiple solutions to this issue and the problem relates to Python.
> 
> Have a look through the log for clues, it can be enabled via the view menu. For my fix I noticed it was using a older version of Python even though I had a more recent version installed. I had multiple versions and QBT picked the oldest version to run with, clearing them out and installing the most current worked.
> 
> On MAC you can try something similar and get the latest version for macOS: https://www.python.org/downloads/macos/

also to me this strange behaviour but in my case python is portable not installed...i do not want to instal it i want to continue to use python portable, in my case is vers 3.8.10

**Comment by Pogman** [comment]
@p060477

Have a look into setting the Python path via QBT Advanced Options.

![Screenshot 2024-10-02 205858](https://github.com/user-attachments/assets/de63b0b0-2127-4557-ab8a-1d2554f7eac0)

**Comment by p060477** [comment]
so many thxs pogman! i really dont know it!
now the problem is the python.exe....the portable vers that i've seems not suitable with this vers 5.00
thxs so many again
cheers

**Comment by mirco982** [comment]
Nothing seems working... I've installed the latest Python stable version 3.12.7, I checked Python path into QBT advanced options (first attempt I left the path empty, then I've set the path /usr/local/bin/python3), rebooted QBT and Mac Mini but I still have the same issues... It seems like the .py plugins are not compatible with QBT v.5.0.0 yet

**Comment by mirco982** [comment]
I just tried with Python v3.13.0rc3 but nothing changes... QBT Log shows me this

02/10/24 22:35 - Plugin yggtracker non supportato.
02/10/24 22:35 - L'estensione di ricerca 'yggtracker.py' contiene stringa di versione non valida ('1.1.')
02/10/24 22:35 - Plugin one337x non supportato.
02/10/24 22:34 - Plugin eztv non supportato.
02/10/24 22:34 - L'estensione di ricerca 'eztv.py' contiene stringa di versione non valida ('1.16<')
02/10/24 22:34 - Mappatura porta UPnP/NAT-PMP riuscita. 
Messaggio: "successfully mapped port using UPnP. external port: UDP/57694"
02/10/24 22:34 - Mappatura porta UPnP/NAT-PMP riuscita. 
Messaggio: "successfully mapped port using UPnP. external port: TCP/57694"
02/10/24 22:34 - Trovato eseguibile Python. 
Nome: "/usr/local/bin/python3". 
Versione: "3.13"

One more time, I think plugins are not yet supported for v5.0.0

I've already also tried to reinstall previous version (4.6.x) but still......... :(

**Comment by p060477** [comment]
> @p060477
> 
> Have a look into setting the Python path via QBT Advanced Options.
> 
> ![Screenshot 2024-10-02 205858](https://private-user-images.githubusercontent.com/7413594/373016812-de63b0b0-2127-4557-ab8a-1d2554f7eac0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MDQwNzYsIm5iZiI6MTcyNzkwMzc3NiwicGF0aCI6Ii83NDEzNTk0LzM3MzAxNjgxMi1kZTYzYjBiMC0yMTI3LTQ1NTctYWI4YS0xZDI1NTRmN2VhYzAuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDJUMjExNjE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmJjMmFmY2U2NjJlMDZjZjkxMGI0ZGM1Mzk1NWZiZGIyODk4ODliNGU1NmJlMTE1YzU3NjcxNzljMTU0MjkzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Ae35KficgeFXcHvdTZv3tQzhDl1kGBA-Q6EhzIVY9wg)

my dear pogman i finally find a portable python.exe vers 12 and put in the path in the adv options as per yr clear instructions
and now ALL goes very well!!
so now with 3.8.10 works vers 4.6.7 and with python 12 works fine also portable 5.0.0
you and xavier2k6 have been my guardian angels!
thxs to you forever
i wish you all the best cause you deserve it!
cheers

**Comment by Pogman** [comment]
> I just tried with Python v3.13.0rc3 but nothing changes... QBT Log shows me this
> 
> 02/10/24 22:35 - Plugin yggtracker non supportato. 02/10/24 22:35 - L'estensione di ricerca 'yggtracker.py' contiene stringa di versione non valida ('1.1.') 02/10/24 22:35 - Plugin one337x non supportato. 02/10/24 22:34 - Plugin eztv non supportato. 02/10/24 22:34 - L'estensione di ricerca 'eztv.py' contiene stringa di versione non valida ('1.16<') 02/10/24 22:34 - Mappatura porta UPnP/NAT-PMP riuscita. Messaggio: "successfully mapped port using UPnP. external port: UDP/57694" 02/10/24 22:34 - Mappatura porta UPnP/NAT-PMP riuscita. Messaggio: "successfully mapped port using UPnP. external port: TCP/57694" 02/10/24 22:34 - Trovato eseguibile Python. Nome: "/usr/local/bin/python3". Versione: "3.13"
> 
> One more time, I think plugins are not yet supported for v5.0.0
> 
> I've already also tried to reinstall previous version (4.6.x) but still......... :(

Your log suggests that it's not accessing / finding the Phyton you have installed. Try rebooting and also try setting the path to Python in QBT advanced options.

Sorry can't help much with macOS stuff. Good luck.

**Comment by faktorqm** [comment]
WOW WOW WOW Pogman is the men! I set the python path and everything starts working!! THANKS A LOT

**Comment by p060477** [comment]
> WOW WOW WOW Pogman is the men! I set the python path and everything starts working!! THANKS A LOT

i repeat and underline that Pogman has really saved all of us!
thxs to you forever and ever

**Comment by sloth456** [comment]
I'm on MacOS and nothing I do seems to work

**Comment by mirco982** [comment]
Same here.
I've found another method to search .torrent file.

**Comment by javyyk** [comment]
MY FIX (update python):

Hi, when I upgraded to version 5 I had this problem.
- What I did first was to check that the log showed the error ‘python not found’.
-> I added the python path to the PATH and the error stopped appearing in the log, but the plugins still didn't load.
- I upgraded Python from 3.8 to 3.13, made sure the PATH pointed to 3.13
-> and the problem was solved.

**Comment by bt4ibwem8** [comment]
I also have problem to get the plugins worked on v5.0.1. From my log:

`(I) 2024-11-09T16:31:23 - Found Python executable. Name: "python3". Version: "3.13"
(I) 2024-11-09T16:31:33 - Plugin "eztv" is outdated, updating to version 1.16
(I) 2024-11-09T16:31:33 - Plugin "jackett" is outdated, updating to version 4.0
(I) 2024-11-09T16:31:33 - Plugin "limetorrents" is outdated, updating to version 4.9
(I) 2024-11-09T16:31:33 - Plugin "piratebay" is outdated, updating to version 3.3
(I) 2024-11-09T16:31:33 - Plugin "solidtorrents" is outdated, updating to version 2.4
(I) 2024-11-09T16:31:33 - Plugin "torlock" is outdated, updating to version 2.24
(I) 2024-11-09T16:31:33 - Plugin "torrentproject" is outdated, updating to version 1.5
(I) 2024-11-09T16:31:33 - Plugin "torrentscsv" is outdated, updating to version 1.4
(I) 2024-11-09T16:31:34 - Plugin torlock is not supported.
(I) 2024-11-09T16:31:34 - Plugin eztv is not supported.
(I) 2024-11-09T16:31:34 - Plugin torrentscsv is not supported.
(I) 2024-11-09T16:31:34 - Plugin torrentproject is not supported.
(I) 2024-11-09T16:31:34 - Plugin limetorrents is not supported.
(I) 2024-11-09T16:31:34 - Plugin jackett is not supported.
(I) 2024-11-09T16:31:34 - Plugin solidtorrents is not supported.
(I) 2024-11-09T16:31:34 - Plugin piratebay is not supported.`

**Comment by Jutakl** [comment]
Unfortunately, I've tried everything in this thread and nothing gives me back my search plugins, which are all still installed but hidden as unsupported and unable to be updated. I have QBT v5.0.2 and only Python 3.13.

With regard to setting the Python executable path in the QBT Advanced Settings, I am not quite sure which path to use, since I am aware of two separate locations to find python.exe, but I think I know which one it wants.

If I use this path:
`C:\Users\MyUsername\AppData\Local\Programs\Python\Python313\python.exe`

then QBT seems to recognize I have Python installed but my search plugins are still not supported and the issue persists.

I'm subscribed to this thread for any more information or corrections in what I'm doing.

**Comment by Acrivec** [comment]
I have renamed the \engines\ folder to \engines1\, started qbit, clicked 'update plugins' (list was empty) and it auto-installed all plugins correctly

**Comment by Jutakl** [comment]
> I have renamed the \engines\ folder to \engines1, started qbit, clicked 'update plugins' (list was empty) and it auto-installed all plugins correctly

Following these instructions exactly, this worked, but it only installed some of my plugins. As an experiment, I copied all the plugins from the engines1 folder that were not installed, and QBT proceeded to not show any plugins at all and give me the same unsupported errors until I removed those copied plugins. Interesting. I removed them and kept only the functional ones for now.

**Comment by peppocola** [comment]
> ###
> **[denkiryu](/denkiryu) ** commented [Oct 1, 2024](#issuecomment-2384315607) •

Thank you, it solved the issue for me

**Comment by AshiqAshref** [comment]
[see if this helps](https://github.com/qbittorrent/search-plugins/issues/353#issuecomment-3074815252)
